import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./storeProvider";
import { auth } from "@root/auth";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Test App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
      <StoreProvider>
        <html lang="en" className="h-screen">
          <body className={`${inter.className} bg-slate-300  h-screen`}>
            <Toaster />
            {children}
          </body>
        </html>
      </StoreProvider>
    </SessionProvider>
  );
}
